// Generated by validation/build_absolute_deck.py — do not edit.
// Deliberately score-free: the page must stay blind to the model.
const ABS_CLIPS = [
  {
    "clip_id": "rectop_rec8_trk29",
    "src": "../realworld/clips/rectop_rec8_trk29.mp4"
  },
  {
    "clip_id": "rectop_rec8_trk34",
    "src": "../realworld/clips/rectop_rec8_trk34.mp4"
  },
  {
    "clip_id": "rectop_rec3_trk34",
    "src": "../realworld/clips/rectop_rec3_trk34.mp4"
  },
  {
    "clip_id": "recbot_rec8_trk21",
    "src": "../realworld/clips/recbot_rec8_trk21.mp4"
  },
  {
    "clip_id": "recbot_rec10_trk10",
    "src": "../realworld/clips/recbot_rec10_trk10.mp4"
  },
  {
    "clip_id": "recbot_rec5_trk22",
    "src": "../realworld/clips/recbot_rec5_trk22.mp4"
  },
  {
    "clip_id": "recbot_rec5_trk37",
    "src": "../realworld/clips/recbot_rec5_trk37.mp4"
  },
  {
    "clip_id": "rectop_rec6_trk44",
    "src": "../realworld/clips/rectop_rec6_trk44.mp4"
  },
  {
    "clip_id": "recbot_rec3_trk14",
    "src": "../realworld/clips/recbot_rec3_trk14.mp4"
  },
  {
    "clip_id": "recbot_rec7_trk74",
    "src": "../realworld/clips/recbot_rec7_trk74.mp4"
  },
  {
    "clip_id": "rectop_rec2_trk4",
    "src": "../realworld/clips/rectop_rec2_trk4.mp4"
  },
  {
    "clip_id": "rectop_rec2_trk22",
    "src": "../realworld/clips/rectop_rec2_trk22.mp4"
  },
  {
    "clip_id": "recbot_rec2_trk65",
    "src": "../realworld/clips/recbot_rec2_trk65.mp4"
  },
  {
    "clip_id": "rectop_rec3_trk17",
    "src": "../realworld/clips/rectop_rec3_trk17.mp4"
  },
  {
    "clip_id": "rectop_rec6_trk57",
    "src": "../realworld/clips/rectop_rec6_trk57.mp4"
  },
  {
    "clip_id": "recbot_rec4_trk42",
    "src": "../realworld/clips/recbot_rec4_trk42.mp4"
  },
  {
    "clip_id": "rectop_rec4_trk10",
    "src": "../realworld/clips/rectop_rec4_trk10.mp4"
  },
  {
    "clip_id": "recbot_rec1_trk34",
    "src": "../realworld/clips/recbot_rec1_trk34.mp4"
  },
  {
    "clip_id": "recbot_rec6_trk11",
    "src": "../realworld/clips/recbot_rec6_trk11.mp4"
  },
  {
    "clip_id": "recbot_rec12_trk10",
    "src": "../realworld/clips/recbot_rec12_trk10.mp4"
  }
];
const ANCHOR_IDS = ["rectop_rec8_trk29", "recbot_rec8_trk21", "rectop_rec3_trk34", "rectop_rec8_trk34"];
